- .github/workflows/build-manual.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- build.sh
- cmd/awl-tray/go.mod
- cmd/awl-tray/go.sum
- go.mod
- go.sum
> Improve ci

- cli/cli.go
- cmd/awl-tray/go.mod
- cmd/awl-tray/main.go
- config/config.go
- config/other.go
- update/update.go
resolves #24 
add awl tray updates
update by button interact with user by dialog windows 
update by ticker show desktop notification when version available
> awl tray update

- api/peers.go
- application.go
- application_test.go
- config/config.go
- service/auth_status.go
> Implement auto accept auth option

- build.sh
- config/other.go
- update/update.go
Before:
```
$ ls -lah build/
total 403M
drwxrwxr-x  2 max max 4.0K дек  6 22:03 .
drwxrwxr-x 26 max max 4.0K дек  6 21:56 ..
-rw-rw-r--  1 max max  67M дек  6 21:59 awl-android-multiarch-v0.4.0-123-g7287fe56.apk
-rwxrwxr-x  1 max max  26M дек  6 21:59 awl-linux-386-v0.4.0-123-g7287fe56
-rwxrwxr-x  1 max max  30M дек  6 21:59 awl-linux-amd64-v0.4.0-123-g7287fe56
-rwxrwxr-x  1 max max  29M дек  6 22:00 awl-linux-arm64-v0.4.0-123-g7287fe56
-rwxrwxr-x  1 max max  26M дек  6 21:59 awl-linux-arm-v0.4.0-123-g7287fe56
-rwxr-xr-x  1 max max  27M дек  6 22:01 awl-tray-linux-386-v0.4.0-123-g7287fe56
-rwxr-xr-x  1 max max  30M дек  6 22:01 awl-tray-linux-amd64-v0.4.0-123-g7287fe56
-rwxr-xr-x  1 max max  29M дек  6 22:03 awl-tray-linux-arm64-v0.4.0-123-g7287fe56
-rwxr-xr-x  1 max max  26M дек  6 22:02 …
```
> build: wrap exe files with archives for release builds

- cmd/awl-tray/go.mod
- cmd/awl-tray/go.sum
- cmd/awl-tray/linux_root_hacks.go
- cmd/awl-tray/linux_root_hacks_other.go
- cmd/awl-tray/main.go
> Fix "Open Web UI" on linux

- cmd/awl-tray/dialogs.go
- cmd/awl-tray/main.go
- cmd/awl-tray/tray.go
> awl-tray: add kdialog

- build.sh
> build: add mipsle and mips for linux awl

- cmd/awl-tray/main.go
- cmd/awl-tray/tray.go
- config/config.go
- config/version.go
- update/update.go
> dirty builds can update now

- .github/workflows/build-manual.yml
- BUILDING.md
- build.sh
> ci: update flutter version in manual build

- application.go
> p2p: use infinite limits for resource manager instead of default

- application.go
- cli/cli.go
- cmd/awl-tray/linux_root_hacks.go
> cmd/awl-tray: automatically elevate privileges to root on linux by executing itself with `pkexec`

- application_test.go
- cmd/awl-tray/linux_root_hacks.go
- config/config.go
- config/other.go
- config/version.go
- config/version_test.go
> cmd/awl-tray: chown config files as user instead of root

- application.go
- awldns/awldns.go
- awldns/awldns_test.go
> awldns: make hosts case-insensitive, add tests

- .github/workflows/test.yml
> ci: fix flaky e2e test

- .github/workflows/test.yml
- api/apiclient/client.go
this should fix errors like this https://github.com/anywherelan/awl/actions/runs/5105728389/jobs/9177555534#step:5:70
for #41
> ci: fix flaky e2e test part 2

- .github/workflows/build-manual.yml
- .github/workflows/test.yml
- application_test.go
> ci: use separate configs for e2e tests for linux and windows

- api/peers.go
- application_test.go
- cli/cli.go
- cli/peers.go
- config/config.go
- entity/api.go
- protocol/protocol.go
- service/auth_status.go
> protocol: add AllowUsingAsExitNode config

- README.md
- install.sh
Add a shell script to help user install awl easier.
> docs: Add script to install awl in Linux

- .github/workflows/build-manual.yml
- go.mod
- go.sum
> ci: sign android release build

- api/settings.go
- application.go
- vpn/iface_windows.go
> api: fix saving config after updating peer info

- api/api.go
- api/const.go
- api/settings.go
- entity/api.go
> api: add methods to list and update socks5 proxy

- cmd/awl-tray/main.go
- cmd/awl-tray/tray.go
add connected peers counter for awl tray
> tray connected peers counter

- application.go
- cmd/awl-tray/tray.go
- service/socks5.go
- socks5/server.go
- vpn/vpn.go
for #102 
see commits descriptions
> socks5: various fixes

- .github/workflows/build-manual.yml
- BUILDING.md
This also adds support for Android 15.
> ci: update to flutter 3.27
